Add docker
Blinnik/java-shareit pull request #4
Opened 2023-07-17 14:46 UTC by Blinnik

Splitting the application into two modules: gateway and server. Containerizing an application using Docker

2023-07-17 20:00 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-07-17 20:00 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +        return post(path, null, null, body);
У тебя всегда `path` это пустая строка.
Так давай уберем этот параметр `post(T body)`, `return post("", null, null, body);`, будем посылать только сущность `post(userDto)`

2023-07-17 20:00 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/common/exception/NotOwnerException.java
> +public class NotOwnerException extends RuntimeException {
Не создавай классов на каждый случай. Пользуйся `NotFoundException`.
А в сообщении детализируй.

2023-07-17 21:02 UTC, Blinnik commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +        return post(path, null, null, body);
Не совсем) В ItemClient в методе createComment используется путь "/{itemId}/comment". Но я в любом случае слегка изменил метод post BaseClient'a)

2023-07-18 17:44 UTC, FanaticFiz approved these changes

2023-07-21 16:57 UTC, merged